name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: chk
        run: ls -R

      - name: upload exe
        uses: actions/upload-artifact@v2
        with:
          name: 'setup'
          path: dist/windows/setup.exe


